title: Climate Informatics 2023
preposition: 'at'
description: 12th International Conference on Climate Informatics, hosted at the University of Cambridge
baseurl: "/climate-informatics-2023" # the subpath of your site, e.g. /blog
url: "https://cambridge-iccs.github.io" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: false

  navigation:
    logo:
      name: CI
      image: 'assets/images/ci-logo.png'
    links:
      - name: "Paper submission"
        relative_url: /submission
      - live:true
      
      - name: "Registration"
        absolute_url: https://onlinesales.admin.cam.ac.uk/conferences-and-events/department-of-applied-mathematics-theoretical-physics-damtp/climate-informatics-conference/climate-informatics-conference-2023
      - live:true
      
      - name: "Agenda"
        absolute_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vS3UIt7aGJe0eQA9PskHcbGthBp6YWTEcm8yDYx0wgGmykqntU7cupBzS2HFDnFGGTaYoAsb06dr01W/pubhtml?gid=1558072167&single=true
      - live:true
   
      - name: "Travel & Accommodation"
        relative_url: /travel
      - live:true

      - name: "Reproducibility Challenge"
        relative_url: /reproducibility-challenge
      - live:true

      - name : "Organising Committees"
        relative_url: /committee
      - live:true

      - name: 'Conference series'
        absolute_url: http://www.climateinformatics.org/
      - live:true
      

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map: true

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true
